from fastapi import FastAPI
from database import Base, engine         #IMPORTING THE DATABASE ENGINE FROM THE DATABASE MODULE
from routers import blog, user, authentication     #IMPORTING THE BLOG AND USER ROUTERS FROM THE ROUTERS MODULE
import models              

app = FastAPI() #CREATING AN INSTANCE OF THE FASTAPI CLASS

Base.metadata.create_all(bind=engine) #CREATING ALL TABLES IN THE DATABASE BASED ON THE MODELS DEFINED, THIS WILL CREATE THE TABLES IF THEY DO NOT EXIST

app.include_router(blog.router)       #INCLUDING THE ROUTER FROM THE BLOG MODULE, THIS ALLOWS US TO ORGANIZE OUR ENDPOINTS IN SEPARATE MODULES AND INCLUDE THEM IN THE MAIN APPLICATION
app.include_router(user.router)       #INCLUDING THE ROUTER FROM THE USER MODULE, THIS ALLOWS US TO ORGANIZE OUR ENDPOINTS IN SEPARATE MODULES AND INCLUDE THEM IN THE MAIN APPLICATION
app.include_router(authentication.router)       