from database import Base                           #IMPORTING THE BASE CLASS FROM THE DATABASE MODULE, THIS IS THE BASE CLASS FOR ALL OUR MODELS
from sqlalchemy import Column, Integer, String, ForeignKey      #IMPORTING THE COLUMN, INTEGER, AND STRING CLASSES FROM SQLALCHEMY, THESE WILL BE USED TO DEFINE THE COLUMNS IN OUR BLOG MODEL
from sqlalchemy.orm import relationship           #IMPORTING THE RELATIONSHIP FUNCTION FROM SQLALCHEMY ORM, THIS CAN BE USED TO DEFINE RELATIONSHIPS BETWEEN TABLES, BUT WE ARE NOT USING IT IN THIS EXAMPLE

class Blog(Base):               #DEFINING THE BLOG MODEL, THIS MODEL INHERITS FROM THE BASE CLASS, THIS MEANS IT WILL BE TREATED AS A TABLE IN THE DATABASE
    __tablename__ = 'blogs'     #SPECIFYING THE NAME OF THE TABLE IN THE DATABASE, THIS IS OPTIONAL, IF NOT SPECIFIED, SQLALCHEMY WILL GENERATE A NAME BASED ON THE CLASS NAME

    id = Column(Integer, primary_key=True, index=True) #
    title = Column(String)
    content = Column(String)
    user_id = Column(Integer, ForeignKey("users.id")) #THIS DEFINES A COLUMN FOR THE USER ID, THIS CAN BE USED TO ASSOCIATE A BLOG POST WITH A USER, THIS IS USEFUL FOR AUTHENTICATION AND AUTHORIZATION PURPOSES

    creator = relationship("User", back_populates="blogs") #THIS DEFINES A RELATIONSHIP TO THE USER MODEL, THIS MEANS THAT EACH BLOG CAN BE ASSOCIATED WITH A USER, THE BACK_POPULATES ARGUMENT SPECIFIES THE NAME OF THE ATTRIBUTE IN THE USER MODEL THAT WILL REFER BACK TO THIS BLOG

class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    password = Column(String)

    blogs = relationship("Blog", back_populates="creator") #THIS DEFINES A RELATIONSHIP TO THE BLOG MODEL, THIS MEANS THAT EACH USER CAN HAVE MULTIPLE BLOGS, THE BACK_POPULATES ARGUMENT SPECIFIES THE NAME OF THE ATTRIBUTE IN THE BLOG MODEL THAT WILL REFER BACK TO THIS USER